### ISSUE TITLE
Command "sudo sh ./[...]" not working on ubuntu 18.04 

### ISSUE THREAD

**Issue by gwMuraro** [RoiArthurB/Side-BunsenLabs_LivePersistent#1]
### Issue 
When executing the command on Ubuntu 18.04 : 
```sh
sudo sh ./bl-livePersistent.sh
```

Shell errors are raised : 
```
./bl-livePersistent.sh: 19: ./bl-livePersistent.sh: [[: not found
./bl-livePersistent.sh: 39: ./bl-livePersistent.sh: [[: not found
This script doesn't support your distro, sorry my friend :/
I've only prepare it for pacman/yay and apt-get !
```

### How can it be solved 
I used another bash interpreter as "bash" for example  : 
```sh 
sudo bash ./bl-livePersistent.sh
```
If it does not work, try by making the ".sh" file executable

**Comment by RoiArthurB** [comment]
Hey, 

I've updated the script and tested on Raspbian. So it should be ok on Ubuntu 18.04 now too :)

To run the script, do as on the tutorial

```
cd /path/to/the/script
sudo sh ./bl-livePersistent.sh
```

If it doesn't work instantly, maybe try to make the file as executable (as you propose me), and rerun the script after.

```
chmod +x bl-livePersistent.sh
sudo sh ./bl-livePersistent.sh
```

I know that Rasbian is less strict than Ubuntu, so tell me if it solved your problem or not ! 
Best ! :)

**Comment by gwMuraro** [comment]
Hello, I tried it and it worked (even without making it executable), thanks ! ;)

**Comment by RoiArthurB** [comment]
Ok perfect !

Thanks for your feedback :)
