### ISSUE TITLE
A lot of errors..

### ISSUE THREAD

**Issue by rbh-se** [RoiArthurB/Side-BunsenLabs_LivePersistent#3]
More errors:
<hr>
Set up the master boot record :
install-mbr:/dev/sdd: Probable detection of modern MBR format which is currently incompatible with install-mbr.  Installing will probably break Windows installations on this system.  Use --force to override.
<hr>
Extraction the ISO :

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=sv_SE.UTF-8,Utf16=on,HugeFiles=on,64 bits,4 CPUs AMD Athlon(tm) II X4 640 Processor (100F53),ASM)

Scanning the drive for archives:
                        
ERROR: No more files
/tmp/toto1233/helium-5-cd-i386.iso

System ERROR:
Unknown error -2147024872
<hr>
Set up persistence :
mv: cannot take status on 'isolinux': The file or directory does not exist   
mv: cannot take status of 'syslinux / isolinux.cfg': The file or directory does not exist   
mv: cannot take status of 'syslinux / isolinux.bin': The file or directory does not exist   
sed: cannot read syslinux / live.cfg: File or directory does not exist   
/ union
s:/syslinux/ldlinux.sys: no match for target
Segmentation fault
syslinux: warning: unable to move ldlinux.sys
s:/syslinux/ldlinux.c32: no match for target
Segmentation fault
syslinux: warning: unable to move ldlinux.c32
<hr>
Cleaning :
umount: ./mnt: mount point not found
rm: cannot delete '/ tmp / toto1233 / mnt': Device or resource busy
<hr>

**Comment by RoiArthurB** [comment]
I don't understand your errors.. 
Could you send me all the full log please? (to display it properly you have to use this character : \` [cf. doc](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code) )
